Update preconditioning
Sparkier/luna pull request #34
Opened 2021-12-04 21:12 UTC by fuzhanrahmanian

* Corrected image initialization

2021-12-06 08:53 UTC, Sparkier requested changes

2021-12-06 08:53 UTC, Sparkier commented on setup.cfg
> +version = 0.6
We should not change this with every PR. We do not know which PR will be merged first. I would say we change this only once we want to release a new version.

2021-12-08 09:53 UTC, Sparkier commented
@fuzhanrahmanian I do not know which changes are still relevant. Can you tell me which commit is the one we want to have from this PR? A lot of them have been addressed in other PRs.

2021-12-08 12:15 UTC, fuzhanrahmanian commented
> @fuzhanrahmanian I do not know which changes are still relevant. Can you tell me which commit is the one we want to have from this PR? A lot of them have been addressed in other PRs.

Just the changes to images.py are relevant

2021-12-08 19:52 UTC, merged